name: Build Common Library

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  Build_Android:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET v9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          dotnet-quality: 'preview'

      - name: Build Console App
        run: |
          dotnet build TooManyCooks.Common/ -c Release